# Generated by Django 4.1.6 on 2023-06-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niños', '0004_alter_niños_tabla2_infotalla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='niños_tabla2',
            name='FechaIngreso',
            field=models.DateField(null=True),
        ),
    ]
