# Generated by Django 4.2.4 on 2023-11-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comidas', '0002_comida_fechaingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comida',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='comida',
            name='informacion',
        ),
        migrations.AddField(
            model_name='comida',
            name='fechaSalida',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='comida',
            name='modoIngreso',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Donacion', 'Donacion')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comida',
            name='modoSalida',
            field=models.CharField(choices=[('Comedor', 'Comedor'), ('Donacion', 'Donacion')], max_length=100, null=True),
        ),
    ]
