# Generated by Django 4.2.1 on 2024-06-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Comidas",
            "0003_remove_comida_descripcion_remove_comida_informacion_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="comida",
            name="peso",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
